### ISSUE TITLE
tool blacklist?

### ISSUE THREAD

**Issue by ghost** [NiChrosia/NoBreak#1]
early game, idgaf if my stone or iron pick breaks, for example

**Comment by NiChrosia** [comment]
Good point. I'll make it so it only prevents enchanted tools from breaking, with a setting for that. There should be a release within a few days with that.

**Comment by NiChrosia** [comment]
Current code now allows breakage of unenchanted tools that aren't diamond or netherite, or anything with a higher mining level than diamond. Now working on the config for that, the release should be done quite soon.

**Comment by NiChrosia** [comment]
Now implemented in the latest commit, will be releasing a version on CF and Modrinth soon.

**Comment by NiChrosia** [comment]
Now released on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/nobreak/files/3409203) and [Modrinth](https://modrinth.com/mod/nobreak/version/i9mw3XOP).
