### ISSUE TITLE
Default options are modified

### ISSUE THREAD

**Issue by Madis0** [NiChrosia/NoBreak#2]
This is my first time using the mod, but I can already see two settings to be modified (aka can be reset).
![Screenshot](https://user-images.githubusercontent.com/8611110/129477309-94d26e9d-f728-425c-864e-7ad36a84202b.png)

**Comment by NiChrosia** [comment]
Not sure how this happened, I'll take a look at that.

**Comment by NiChrosia** [comment]
Fixed this in the latest commit
