### ISSUE TITLE
Blacklist has confusing UX

### ISSUE THREAD

**Issue by Madis0** [NiChrosia/NoBreak#3]
* It is not initially obvious that there is a blacklist in the first place, before accidentally pressing "b" - please list the items that are in the list somewhere in settings.
* There should not be any items in the blacklist by default. If I installed this mod, I expect it to work _by default_ on wooden, stone, iron and golden items as well.
* Perhaps add buttons to settings to add all/remove all tools of a tier to blacklist? And a button to clear the blacklist altogether.
* The blacklist and "allow diamond tools or better to break" seem like conflicting options, perhaps the latter should be removed?

**Comment by NiChrosia** [comment]
Good point. I'll try to add a new GUI that shows the blacklisted items, as well as presets with similar features to the current state, that won't be enabled by default.

**Comment by NiChrosia** [comment]
The code for presets is now implemented, the default key to open it is "O"
Blacklist screen: (shows items on the left, and has the preset button on the right.)
![image](https://user-images.githubusercontent.com/57579569/129593020-fb00c079-a8e3-4a59-b5ca-c85da9a7dc74.png)
Preset screen: (Icon & name on the button, description to the right of it, back button on the bottom, leads back to the blacklist screen.)
![image](https://user-images.githubusercontent.com/57579569/129593078-b8accd1f-3862-464b-9caa-d6594b14530d.png)

**Comment by Madis0** [comment]
Okay, I've tested the new build and I have more feedback regarding this:

- Blacklist window doesn't need a keybind, a button in mod options would suffice
- Toggling blacklist per item can have a keybind, but if your GUI library supports item selection, then preferably integrate that as well/instead of the keybind (you choose which), because it makes more sense to manage individual items in the blacklist GUI than in-game
- More blacklist presets and a way to mix and match them. E.g. diamond/iron/... items (add presets individually per-tier), throwables (bow, crossbow, trident), other tools, modded items (auto-detect)... So if I want to un-blacklist all gold tools for example, it would be easier than it is now.

**Comment by Madis0** [comment]
Alternatively, what if you don't have any presets as all, just a list of item icons that are categorized as "tool" (have a durability) and people simply click to enable/disable them.

**Comment by NiChrosia** [comment]
> Okay, I've tested the new build and I have more feedback regarding this:
> 
> * Blacklist window doesn't need a keybind, a button in mod options would suffice

I agree, but I don't know where to put it without having an ugly toggle that opens it when changed

> * Toggling blacklist per item can have a keybind, but if your GUI library supports item selection, then preferably integrate that as well/instead of the keybind (you choose which), because it makes more sense to manage individual items in the blacklist GUI than in-game

I don't think LibGUI supports that

> * More blacklist presets and a way to mix and match them. E.g. diamond/iron/... items (add presets individually per-tier), throwables (bow, crossbow, trident), other tools, modded items (auto-detect)... So if I want to un-blacklist all gold tools for example, it would be easier than it is now.

Good idea, I'll make the presets be an array rather than a single variable, and make modifying it not create a new copy of it, and instead have a separate "preset" for the manual selection.

> Alternatively, what if you don't have any presets as all, just a list of item icons that are categorized as "tool" (have a durability) and people simply click to enable/disable them.

That would also work, especially when used in combination with tabs.

**Comment by NiChrosia** [comment]
New presets for wooden-diamond (based on mining level), as well as throwables have been added, will be releasing a new version shortly.

**Comment by Madis0** [comment]
> I agree, but I don't know where to put it without having an ugly toggle that opens it when changed

The creator of Cloth Config told me to look at how REI adds the "reload plugins" button, which seems to be this:

https://github.com/shedaniel/RoughlyEnoughItems/blob/6.x-1.17/runtime/src/main/java/me/shedaniel/rei/impl/client/config/entries/ReloadPluginsEntry.java

I know it is in Java but I'm sure you can use it in Kotlin as well. (I don't have much experience with Kotlin so I can't PR unfortunately)
