### ISSUE TITLE
Armor compatibility

### ISSUE THREAD

**Issue by Madis0** [NiChrosia/NoBreak#4]
It would be great if this worked on armor as well to some extent. 

I understand that automatic armor management could trigger anticheats, but how about doing it automatically once the player next opens the inventory screen: "Your (armor item) is about to break. Press (inventory key) to stop wearing the item."

Because the player may not do it in time, there could also be a "padding" of 1-10 durability where this feature would activate, as opposed to handheld items, where it only occurs on 1.

**Comment by NiChrosia** [comment]
The thing about this situation, is that if your armor was already really low, you're almost guaranteed to be in a PV(P/E) situation, in which case it's rather problematic if the mod were to take off your armor. This could be "fixed" by making it automatically put on a new set, but at that point it's cheating. I'm not sure of any alternatives that would make this viable.

**Comment by Madis0** [comment]
Yeah, putting on a new set would be out of scope. 
I'm thinking more like PvE fights when having e.g. thorns 3 on armor items and one would rather take a bigger damage (or even die and walk back) than lose a well-enchanted, mendable item. 
In PvP this would mean that your opponent gets your armor, which may or may not be desirable (e.g. maybe they'll sell you that item back instead of having to recreate it), depending on the situation.

And obviously this would be opt-in.

Edit: perhaps even detect the damage source and only do this for non-player entities.

**Comment by NiChrosia** [comment]
Yeah, that sounds good, I'll probably have some sort of dropdown to select whether to allow taking it off for players, entities, none, and both.

**Comment by NiChrosia** [comment]
To be honest, I'm not sure I want to mess with the code for manipulating the inventory, as it seems to be incredibly "low-level", as in you have to manually send packets each time you click a slot.
Code example from Tweakeroo:
```java
    private static void swapItemToHand(PlayerEntity player, Hand hand, int slotNumber) {
        if (slotNumber != -1 && player.currentScreenHandler == player.playerScreenHandler) {
            MinecraftClient mc = MinecraftClient.getInstance();
            ScreenHandler container = player.playerScreenHandler;

            if (hand == Hand.MAIN_HAND) {
                int currentHotbarSlot = player.getInventory().selectedSlot;
                Slot slot = container.getSlot(slotNumber);

                if (slot != null && isHotbarSlot(slot)) {
                    player.getInventory().selectedSlot = slotNumber - 36;
                    mc.getNetworkHandler().sendPacket(new UpdateSelectedSlotC2SPacket(player.getInventory().selectedSlot));
                } else {
                    mc.interactionManager.clickSlot(container.syncId, slotNumber, currentHotbarSlot, SlotActionType.SWAP, mc.player);
                }
            } else if (hand == Hand.OFF_HAND) {
                int currentHotbarSlot = player.getInventory().selectedSlot;
                // Swap the requested slot to the current hotbar slot
                mc.interactionManager.clickSlot(container.syncId, slotNumber, currentHotbarSlot, SlotActionType.SWAP, mc.player);

                // Swap the requested item from the hotbar slot to the offhand
                mc.interactionManager.clickSlot(container.syncId, 45, currentHotbarSlot, SlotActionType.SWAP, mc.player);

                // Swap the original item back to the hotbar slot
                mc.interactionManager.clickSlot(container.syncId, slotNumber, currentHotbarSlot, SlotActionType.SWAP, mc.player);
            }
        }
    }

**Comment by NiChrosia** [comment]
I'll go ahead and publish a new release as soon as I implement a setting to toggle attacking your own pets, as well as one for attacking neutral until provoked mobs.

**Comment by NiChrosia** [comment]
..nevermind, it seems there's some sort of issue with the return value for using an item on a block and attacking entities, I'll won't release it for now as using items or attacking entities is literally impossible.

Overall status report: Mining blocks and the blacklist work correctly, but attacking entities and using items on blocks is utterly broken, and I have no idea why.

**Comment by NiChrosia** [comment]
There's now a new [workflow](https://github.com/NiChrosia/NoBreak/actions/runs/1137156521) that has the latest JAR with the testing features, I'll also make one for disabling the entity and use features so you can use that in the meantime until I can eventually fix this (as in multiple days, or weeks, etc.)
Edit: here is the new [workflow](https://github.com/NiChrosia/NoBreak/runs/3344952114) with the specified features disabled.

**Comment by Madis0** [comment]
> To be honest, I'm not sure I want to mess with the code for manipulating the inventory, as it seems to be incredibly "low-level", as in you have to manually send packets each time you click a slot.

But it would only take one shift-click in this mod? I can see Tweakaroo is doing 3 clicks here.

**Comment by NiChrosia** [comment]
> > To be honest, I'm not sure I want to mess with the code for manipulating the inventory, as it seems to be incredibly "low-level", as in you have to manually send packets each time you click a slot.
> 
> But it would only take one shift-click in this mod? I can see Tweakaroo is doing 3 clicks here.

Good point, I only focused on the individual complexity of a single line, so I'll just write a minor wrapper to make it less ugly.

**Comment by NiChrosia** [comment]
I have no idea how to work with inventory code, and as I probably won't be using it myself since I rarely PVP, I'll discontinue this. If you want to try to make it work, feel free to send a PR. The area where you'd add stuff would be in NBEvents.kt, in the area with the `it.player?.let tick@{ player ->` and the comment.
