### ISSUE TITLE
Option for enchanted tools only

### ISSUE THREAD

**Issue by Madis0** [NiChrosia/NoBreak#7]
At some point between 2.0.0 and 2.1.1 that feature got lost. Even with the new blacklist system it could be nice to only protect enchanted items, if so desired (opt-in).

**Comment by NiChrosia** [comment]
It's still supported, there just aren't any presets that have it.

**Comment by NiChrosia** [comment]
I'll make it have a button by the preset button, to toggle between allowing all tools to break, and only allowing unenchanted tools to break. ETA: soon™️

**Comment by NiChrosia** [comment]
Nearly done with implementation, just need to fix a bug with all of the items going into one spot. Unfortunately, I have some activity to do, so that'll have to wait for nearly 16 hours.

**Comment by NiChrosia** [comment]
Now implemented, just need to iron out a few small bugs like the system allowing duplicate blacklist items, and then I'll publish a release.

**Comment by NiChrosia** [comment]
Done. ~~Now to release on MR and CF.~~ Now released on [Modrinth](https://modrinth.com/mod/nobreak/version/CgZ3X5Yw) and [Curseforge](https://www.curseforge.com/minecraft/mc-mods/nobreak/files/3457041).
