### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Phoenix-Starlight** [NiChrosia/NoBreak#8]
I was wondering whether you could change it from .dat to .json, thanks!

**Comment by NiChrosia** [comment]
Yeah, I'll implement that soon. (Within 1-3 days)

**Comment by NiChrosia** [comment]
Now implemented in the latest commit (thought that implement was a issue closing keyword), ~~will be publishing new version to CF & MR shortly~~ [Curseforge](https://www.curseforge.com/minecraft/mc-mods/nobreak/files/3455882) and [Modrinth file](https://modrinth.com/mod/nobreak/version/GQlq7FmM)
